language: python

services:
  - docker

script:
  - echo "hello"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  docker push USER/REPO
#  - docker build -t assassinen/grid_bot_client:latest .