language: python

services:
  - docker

script:
  - echo "hello"
  - echo $DOCKER_USERNAME
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t assassinen/grid_bot_client:latest .
  - docker push assassinen/grid_bot_client:latest