name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: assassinen
    - name: Build the Docker image
      run: |
          echo test, and deploy your project.
          echo ${{ secrets.GITHUB_TOKEN }}
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
